"use client";

import { useState } from "react";
import { Check, ChefHat, Clock3, Coffee, Flame, MoreHorizontal, PackageCheck, Play, Volume2 } from "lucide-react";

const initialOrders = [
  { id: "#KOR-1048", table: "Стол 12", age: "2 мин", state: "new", items: [["Трюфельный бургер", "× 2"], ["Картофель фри", "× 1"]], note: "Бургер — medium, без лука" },
  { id: "#KOR-1045", table: "Стол 04", age: "8 мин", state: "cooking", items: [["Лосось мисо", "× 1"], ["Матча-тоник", "× 1"]], note: "" },
  { id: "#KOR-1044", table: "Стол 09", age: "15 мин", state: "cooking", items: [["Паста с креветкой", "× 2"], ["Тирамису KÖR", "× 2"]], note: "Одну пасту без чили" },
];

export default function KitchenPage() { const [orders, setOrders] = useState(initialOrders); function advance(id: string) { setOrders((all) => all.map((order) => order.id === id ? { ...order, state: order.state === "new" ? "cooking" : "ready" } : order)); } return <main className="station-shell"><header className="station-topbar"><a className="brand" href="/"><span className="brand-mark"><Coffee size={17} /></span>KÖR</a><div className="station-title"><ChefHat size={17} /> Kitchen display <span className="live-chip"><i /> LIVE</span></div><div className="station-actions"><span><Clock3 size={15} /> Среднее время: <b>18 мин</b></span><button><Volume2 size={17} /></button><div className="station-user">AK</div></div></header><div className="station-main"><div className="station-heading"><div><p className="section-kicker">ПОНЕДЕЛЬНИК · СМЕНА 09:00—23:00</p><h1>Добрый день, команда.</h1></div><div className="station-date">Сегодня, 14 октября <span>·</span> 12:44</div></div><div className="kitchen-stats"><div><span className="stat-dot orange" />Новые <b>{orders.filter((o) => o.state === "new").length}</b></div><div><span className="stat-dot amber" />Готовятся <b>{orders.filter((o) => o.state === "cooking").length}</b></div><div><span className="stat-dot green" />Готовы <b>{orders.filter((o) => o.state === "ready").length}</b></div><div className="kitchen-note"><Flame size={15} /> Загруженность кухни <b>64%</b><span className="load-bar"><i /></span></div></div><div className="kitchen-board"><div className="kitchen-column"><div className="column-heading"><h2>Новые <span>{orders.filter((o) => o.state === "new").length}</span></h2><MoreHorizontal size={18} /></div>{orders.filter((o) => o.state === "new").map((order) => <KitchenCard key={order.id} order={order} onAdvance={advance} />)}</div><div className="kitchen-column cooking-column"><div className="column-heading"><h2>Готовятся <span>{orders.filter((o) => o.state === "cooking").length}</span></h2><MoreHorizontal size={18} /></div>{orders.filter((o) => o.state === "cooking").map((order) => <KitchenCard key={order.id} order={order} onAdvance={advance} />)}</div><div className="kitchen-column ready-column"><div className="column-heading"><h2>Готовы <span>{orders.filter((o) => o.state === "ready").length}</span></h2><MoreHorizontal size={18} /></div>{orders.filter((o) => o.state === "ready").map((order) => <KitchenCard key={order.id} order={order} onAdvance={advance} />)}</div></div></div></main>; }

function KitchenCard({ order, onAdvance }: { order: typeof initialOrders[number]; onAdvance: (id: string) => void }) { const next = order.state === "new" ? "Взять в работу" : order.state === "cooking" ? "Заказ готов" : "Готово"; return <article className={`kitchen-order ${order.state}`}><div className="kitchen-order-head"><strong>{order.id}</strong><span>{order.age}</span></div><div className="kitchen-table"><span>{order.table}</span><i /> <small>DINE IN</small></div><div className="kitchen-items">{order.items.map(([name, quantity]) => <div key={name}><b>{quantity}</b><span>{name}</span></div>)}</div>{order.note && <div className="kitchen-note-text">{order.note}</div>}<button className="kitchen-advance" onClick={() => onAdvance(order.id)}>{order.state === "new" ? <Play size={14} fill="currentColor" /> : order.state === "cooking" ? <Check size={15} /> : <PackageCheck size={15} />}{next}</button></article>; }
