"use client";

import { use, useEffect, useMemo, useState } from "react";
import { ArrowLeft, Check, ChefHat, Clock3, Coffee, MapPin, PackageCheck, ShoppingBag } from "lucide-react";

type TrackingOrder = { id: string; displayNumber: string; status: "NEW" | "COOKING" | "READY" | "DELIVERING" | "COMPLETED" | "CANCELLED"; estimatedMinutes: number | null; total: number; fulfillment: "DINE_IN" | "PICKUP"; tableNumber?: string; restaurant: { name: string; address: string }; items: Array<{ nameSnapshot: string; quantity: number; unitPrice: number }> };
const getApiBase = () => process.env.NEXT_PUBLIC_API_URL || (typeof window !== "undefined" && window.location.port === "3000" ? `http://${window.location.hostname}:4000` : "");
const statusOrder = ["NEW", "COOKING", "READY", "DELIVERING", "COMPLETED"] as const;
const statusCopy: Record<string, { title: string; detail: string }> = { NEW: { title: "Заказ принят", detail: "Мы передали заказ на кухню" }, COOKING: { title: "Готовится", detail: "Кухня уже готовит ваш заказ" }, READY: { title: "Готово", detail: "Заказ ждёт выдачи" }, DELIVERING: { title: "Несём к столу", detail: "Официант уже забирает заказ" }, COMPLETED: { title: "Заказ завершён", detail: "Приятного аппетита!" }, CANCELLED: { title: "Заказ отменён", detail: "Если это ошибка, свяжитесь с рестораном" } };
const stepIcons = [ShoppingBag, ChefHat, PackageCheck, Check];

export default function OrderTrackingPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params); const [order, setOrder] = useState<TrackingOrder | null>(null); const [loading, setLoading] = useState(true); const [showDetails, setShowDetails] = useState(false);
  useEffect(() => { let cancelled = false; const load = async () => { try { const response = await fetch(`${getApiBase()}/api/v1/orders/track/${encodeURIComponent(id)}`, { cache: "no-store" }); if (!response.ok) throw new Error("Order not found"); const payload = await response.json(); if (!cancelled) setOrder(payload.data); } catch { if (!cancelled) setOrder(null); } finally { if (!cancelled) setLoading(false); } }; load(); const timer = window.setInterval(load, 5000); return () => { cancelled = true; window.clearInterval(timer); }; }, [id]);
  const activeIndex = useMemo(() => order ? Math.max(0, statusOrder.indexOf(order.status as typeof statusOrder[number])) : 1, [order]); const current = statusCopy[order?.status ?? "COOKING"]; const tableLabel = order?.fulfillment === "DINE_IN" ? `СТОЛ ${order.tableNumber ?? "—"}` : "С СОБОЙ"; const menuHref = `/menu/coffee-house${order?.tableNumber ? `?table=${order.tableNumber}` : ""}`;
  const steps = [{ title: "Заказ принят", detail: "Мы получили ваш заказ" }, { title: "Готовится", detail: "Кухня уже работает" }, { title: order?.fulfillment === "DINE_IN" ? "Передан официанту" : "Готов к выдаче", detail: order?.fulfillment === "DINE_IN" ? "Скоро будет у вашего стола" : "Можно забрать на кассе" }, { title: "Заказ завершён", detail: "Приятного аппетита!" }];
  const money = (amount: number) => `${new Intl.NumberFormat("ru-RU").format(amount)} ₸`;
  return <main className="tracking-shell"><header className="tracking-topbar"><a className="brand" href={menuHref}><span className="brand-mark"><Coffee size={17} /></span>KÖR</a><span className="table-status"><span className="live-dot" /> Статус обновляется автоматически</span></header><div className="tracking-content"><a className="back-link" href={menuHref}><ArrowLeft size={15} /> Вернуться в меню</a>{loading && !order ? <div className="tracking-loading">Загружаем статус заказа…</div> : <><div className="tracking-hero"><div><p className="section-kicker">{order?.restaurant.name ?? "COFFEE HOUSE"} · {tableLabel}</p><h1>Ваш заказ<br /><em>{current.title.toLowerCase()}.</em></h1><p>{current.detail}. Статус обновляется автоматически — страницу обновлять не нужно.</p></div><div className="tracking-number"><span>Номер заказа</span><strong>#{order?.displayNumber ?? id.toUpperCase()}</strong><small><MapPin size={12} /> {order?.restaurant.address ?? "Жарокова, 41"}</small></div></div><section className="tracking-grid"><div className="status-card"><div className="status-card-head"><div><span className="live-chip"><i /> LIVE STATUS</span><h2>{order?.estimatedMinutes ? `Примерно ${order.estimatedMinutes} минут` : current.title}</h2></div><div className="status-clock"><Clock3 size={18} /><span>обновлено<br /><b>только что</b></span></div></div><div className="tracking-steps">{steps.map((step, index) => { const Icon = stepIcons[index]; const active = index <= Math.min(activeIndex, steps.length - 1); return <div className={`tracking-step ${active ? "active" : ""}`} key={step.title}><div className="step-icon"><Icon size={16} /></div><div className="step-copy"><strong>{step.title}</strong><span>{step.detail}</span></div><time>{active ? "✓" : "—"}</time>{index < steps.length - 1 && <i className={index < activeIndex ? "filled" : ""} />}</div>; })}</div></div><div className="order-summary-card"><div className="summary-head"><h2>Ваш заказ</h2><button onClick={() => setShowDetails(!showDetails)}>{showDetails ? "Скрыть" : "Детали"}</button></div>{order?.items?.length ? order.items.map((item) => <div className="summary-line" key={`${item.nameSnapshot}-${item.quantity}`}><span><b>{item.quantity}×</b> {item.nameSnapshot}</span><strong>{money(item.unitPrice * item.quantity)}</strong></div>) : <div className="summary-line"><span>Состав заказа</span><strong>—</strong></div>}{showDetails && <div className="summary-extra"><span>{tableLabel}</span><span>{order?.fulfillment === "DINE_IN" ? "В зале · оплата при заказе" : "Самовывоз"}</span></div>}<div className="summary-total"><span>Итого</span><strong>{money(order?.total ?? 0)}</strong></div><button className="tracking-help">Нужна помощь? <span>Связаться с нами →</span></button></div></section></>}</div></main>;
}
