"use client";

import { useEffect, useMemo, useState } from "react";
import {
  ArrowRight, Check, ChevronDown, Clock3, Coffee, Heart, Minus, Plus, Search,
  ShoppingBag, SlidersHorizontal, Sparkles, Star, X, Utensils, Leaf,
} from "lucide-react";
import type { CartLine, Locale, Product } from "@qr-menu/types";

const products: Product[] = [
  { id: "truffle-burger", category: "popular", name: { ru: "Трюфельный бургер", kk: "Трюфельді бургер", en: "Truffle burger" }, description: { ru: "Мраморная говядина, чеддер, трюфельный айоли", kk: "Мәрмәр сиыр еті, чеддер, трюфельді айоли", en: "Wagyu beef, cheddar, truffle aioli" }, price: 4900, image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=85", tags: ["chef", "popular"], prepMinutes: 18, available: true },
  { id: "burrata", category: "popular", name: { ru: "Буррата & томаты", kk: "Буррата және қызанақ", en: "Burrata & tomatoes" }, description: { ru: "Сливочная буррата, печёные томаты, базилик", kk: "Кілегейлі буррата, пісірілген қызанақ, базилик", en: "Creamy burrata, roasted tomatoes, basil" }, price: 3700, image: "https://images.unsplash.com/photo-1608897013039-887f21d8c804?auto=format&fit=crop&w=900&q=85", tags: ["vegetarian", "new"], prepMinutes: 8, available: true },
  { id: "salmon", category: "mains", name: { ru: "Лосось мисо", kk: "Мисо қосылған лосось", en: "Miso salmon" }, description: { ru: "Глазированный лосось, жасминовый рис, эдамаме", kk: "Жылтыратылған лосось, жасмин күріші, эдамаме", en: "Glazed salmon, jasmine rice, edamame" }, price: 5600, image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=900&q=85", tags: ["chef"], prepMinutes: 22, available: true },
  { id: "pasta", category: "mains", name: { ru: "Паста с креветкой", kk: "Асшаян қосылған паста", en: "Prawn pasta" }, description: { ru: "Лингвини, тигровые креветки, бисque, чили", kk: "Лингвини, жолбарыс асшаяны, бисque, чили", en: "Linguine, tiger prawns, bisque, chilli" }, price: 4600, image: "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?auto=format&fit=crop&w=900&q=85", tags: [], prepMinutes: 17, available: true },
  { id: "matcha", category: "drinks", name: { ru: "Матча-тоник", kk: "Матча-тоник", en: "Matcha tonic" }, description: { ru: "Цитрусовая матча, тоник, лёд", kk: "Цитрус матча, тоник, мұз", en: "Citrus matcha, tonic, ice" }, price: 1800, image: "https://images.unsplash.com/photo-1515823662972-da6a2e4d3002?auto=format&fit=crop&w=900&q=85", tags: ["new", "vegetarian"], prepMinutes: 4, available: true },
  { id: "tiramisu", category: "desserts", name: { ru: "Тирамису KÖR", kk: "KÖR тирамисуы", en: "KÖR tiramisu" }, description: { ru: "Маскарпоне, эспрессо, какао", kk: "Маскарпоне, эспрессо, какао", en: "Mascarpone, espresso, cocoa" }, price: 2100, image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=900&q=85", tags: ["popular"], prepMinutes: 3, available: true },
];

const copy = {
  ru: { menu: "Меню", search: "Найти блюдо", popular: "Популярное", mains: "Основные блюда", drinks: "Напитки", desserts: "Десерты", all: "Всё меню", add: "Добавить", cart: "Корзина", total: "Итого", order: "Оформить заказ", empty: "Корзина пока пуста", emptyHint: "Добавьте что-нибудь вкусное — кухня уже готова", table: "Стол", hall: "Зал", open: "Открыто до 23:00", vegan: "Вегетарианское", new: "Новинка", chef: "Выбор шефа", delivery: "Принесите заказ", pickup: "Заберу сам", note: "Комментарий к заказу", language: "Язык", chooseTable: "Выберите стол", chooseTableHint: "Укажите, за каким столом вы сидите", free: "Свободен", selected: "Выбран" },
  kk: { menu: "Мәзір", search: "Тағам іздеу", popular: "Танымал", mains: "Негізгі тағамдар", drinks: "Сусындар", desserts: "Десерттер", all: "Барлық мәзір", add: "Қосу", cart: "Себет", total: "Барлығы", order: "Тапсырыс беру", empty: "Себет бос", emptyHint: "Дәмді тағам қосыңыз", table: "Үстел", hall: "Зал", open: "23:00-ге дейін ашық", vegan: "Вегетариандық", new: "Жаңа", chef: "Шеф таңдауы", delivery: "Тапсырысты әкеліңіз", pickup: "Өзім аламын", note: "Тапсырысқа түсініктеме", language: "Тіл", chooseTable: "Үстелді таңдаңыз", chooseTableHint: "Қай үстелде отырғаныңызды көрсетіңіз", free: "Бос", selected: "Таңдалды" },
  en: { menu: "Menu", search: "Find a dish", popular: "Popular", mains: "Mains", drinks: "Drinks", desserts: "Desserts", all: "Full menu", add: "Add", cart: "Basket", total: "Total", order: "Place order", empty: "Your basket is empty", emptyHint: "Add something delicious — the kitchen is ready", table: "Table", hall: "Floor", open: "Open until 23:00", vegan: "Vegetarian", new: "New", chef: "Chef's pick", delivery: "Bring it to my table", pickup: "I'll pick it up", note: "Order note", language: "Language", chooseTable: "Choose a table", chooseTableHint: "Tell us where you are sitting", free: "Available", selected: "Selected" },
};

const money = (amount: number) => new Intl.NumberFormat("ru-RU").format(amount) + " ₸";
const getApiBase = () => process.env.NEXT_PUBLIC_API_URL || (typeof window !== "undefined" && window.location.port === "3000" ? `http://${window.location.hostname}:4000` : "");

export default function MenuPage() {
  const [locale, setLocale] = useState<Locale>("ru");
  const [category, setCategory] = useState("all");
  const [query, setQuery] = useState("");
  const [cart, setCart] = useState<CartLine[]>([]);
  const [menuProducts, setMenuProducts] = useState<Product[]>(products);
  const [restaurantId, setRestaurantId] = useState<string>();
  const [orderError, setOrderError] = useState("");
  const [isCartOpen, setCartOpen] = useState(false);
  const [isOrderOpen, setOrderOpen] = useState(false);
  const [ordered, setOrdered] = useState(false);
  const t = copy[locale];
  const tableFromUrl = new URLSearchParams(typeof window !== "undefined" ? window.location.search : "").get("table") || "";
  const [table, setTable] = useState(tableFromUrl);
  const [hallOpen, setHallOpen] = useState(false);
  const [fulfillment, setFulfillment] = useState<"DINE_IN" | "PICKUP">("DINE_IN");
  const [orderNumber, setOrderNumber] = useState("");
  const [trackingToken, setTrackingToken] = useState("");
  const tableOptions = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"];
  useEffect(() => { const apiUrl = getApiBase(); fetch(`${apiUrl}/api/v1/restaurants/coffee-house/menu`).then((response) => response.ok ? response.json() : Promise.reject(new Error("menu unavailable"))).then((payload: { data: { id: string; categories: Array<{ slug: string; products: Array<{ id: string; nameRu: string; nameKk: string; nameEn: string; descriptionRu: string; descriptionKk: string; descriptionEn: string; price: number; imageUrl: string | null; prepMinutes: number; isPopular: boolean; isNew: boolean; isChefChoice: boolean; }> }> } }) => { setRestaurantId(payload.data.id); const imageFallbacks = products.map((product) => product.image); const fromApi = payload.data.categories.flatMap((category) => category.products.map((product, index) => ({ id: product.id, category: category.slug, name: { ru: product.nameRu, kk: product.nameKk, en: product.nameEn }, description: { ru: product.descriptionRu, kk: product.descriptionKk, en: product.descriptionEn }, price: product.price, image: product.imageUrl ?? imageFallbacks[index % imageFallbacks.length], tags: [product.isPopular ? "popular" : "", product.isNew ? "new" : "", product.isChefChoice ? "chef" : ""].filter(Boolean), prepMinutes: product.prepMinutes, available: true }))); if (fromApi.length) setMenuProducts(fromApi); }).catch(() => undefined); }, []);
  async function submitOrder() { if (!restaurantId) { setOrderError("Не удалось подключиться к ресторану. Попробуйте ещё раз."); return; } if (fulfillment === "DINE_IN" && !table) { setOrderError("Сначала выберите стол в зале."); setHallOpen(true); return; } setOrderError(""); const response = await fetch(`${getApiBase()}/api/v1/orders`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ restaurantId, tableNumber: fulfillment === "DINE_IN" ? table : undefined, fulfillment, items: cart.map((item) => ({ productId: item.id, quantity: item.quantity, modifierIds: [] })) }) }); if (!response.ok) { setOrderError("Не удалось оформить заказ. Проверьте корзину и попробуйте снова."); return; } const payload = await response.json(); setOrderNumber(payload.data.displayNumber); setTrackingToken(payload.data.trackingToken); setOrdered(true); }
  const filtered = useMemo(() => menuProducts.filter((p) => (category === "all" || category === "popular" ? category === "all" || (category === "popular" ? p.tags.includes("popular") : p.category === category) : p.category === category) && p.name[locale].toLowerCase().includes(query.toLowerCase())), [category, locale, menuProducts, query]);
  const count = cart.reduce((sum, item) => sum + item.quantity, 0);
  const total = cart.reduce((sum, item) => sum + item.price * item.quantity, 0);

  function add(product: Product) { setCart((items) => { const found = items.find((item) => item.id === product.id); return found ? items.map((item) => item.id === product.id ? { ...item, quantity: item.quantity + 1 } : item) : [...items, { ...product, quantity: 1, modifiers: [] }]; }); }
  function change(id: string, direction: number) { setCart((items) => items.flatMap((item) => item.id === id ? (item.quantity + direction > 0 ? [{ ...item, quantity: item.quantity + direction }] : []) : [item])); }

  return <main className="customer-shell">
    <header className="topbar">
      <a className="brand" href="/menu/coffee-house"><span className="brand-mark"><Coffee size={17} /></span><span>KÖR</span></a>
      <div className="topbar-right"><button className="table-status table-picker-trigger" onClick={() => setHallOpen(true)}><span className="live-dot" /> {t.hall} {table || "—"}</button>{orderNumber && <a className="order-status-link" href={`/order/${orderNumber}`}><Clock3 size={14} /> Статус заказа</a>}<div className="lang-switch">{(["ru", "kk", "en"] as Locale[]).map((lang) => <button key={lang} className={locale === lang ? "active" : ""} onClick={() => setLocale(lang)}>{lang.toUpperCase()}</button>)}</div><button className="icon-button" aria-label={t.cart} onClick={() => setCartOpen(true)}><ShoppingBag size={19} />{count > 0 && <b className="cart-count">{count}</b>}</button></div>
    </header>
    <section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-line" /> EST. 2018 · ALMATY</div><h1>Good food.<br /><em>Good mood.</em></h1><p>Кофейня и кухня с характером. Выбирайте, мы приготовим.</p><div className="restaurant-meta"><span><span className="open-indicator" /> {t.open}</span><span>•</span><span>Жарокова, 41</span></div></div><div className="hero-art"><div className="hero-orb" /><div className="hero-card"><span>Сегодня рекомендуем</span><strong>Трюфельный<br />бургер</strong><small>от 4 900 ₸ <ArrowRight size={14} /></small></div></div></section>
    <section className="menu-toolbar"><div><p className="section-kicker">{t.menu}</p><h2>Choose your <em>moment.</em></h2></div><div className="search-box"><Search size={18} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder={t.search} /><button aria-label="Filters"><SlidersHorizontal size={17} /></button></div></section>
    <nav className="category-tabs" aria-label="Menu categories">{[["all", t.all], ["popular", t.popular], ["mains", t.mains], ["drinks", t.drinks], ["desserts", t.desserts]].map(([id, label]) => <button key={id} className={category === id ? "selected" : ""} onClick={() => setCategory(id)}>{label}{id === "popular" && <Sparkles size={13} />}</button>)}</nav>
    <section className="product-grid">{filtered.map((product, index) => <article className={`product-card ${index === 0 ? "featured-card" : ""}`} key={product.id}><div className="product-photo" style={{ backgroundImage: `url(${product.image})` }}><div className="photo-overlay" />{product.tags.includes("chef") && <span className="product-tag chef"><Star size={11} fill="currentColor" /> {t.chef}</span>}{product.tags.includes("new") && <span className="product-tag new">{t.new}</span>}<button className="heart-button" aria-label="Add to favourites"><Heart size={17} /></button></div><div className="product-info"><div className="product-title-row"><h3>{product.name[locale]}</h3><strong>{money(product.price)}</strong></div><p>{product.description[locale]}</p><div className="product-footer"><span className="prep"><Clock3 size={14} /> {product.prepMinutes} min {product.tags.includes("vegetarian") && <><span className="footer-divider" /><Leaf size={14} /> {t.vegan}</>}</span><button className="add-button" onClick={() => add(product)}>{t.add} <Plus size={15} /></button></div></div></article>)}</section>
    {cart.length > 0 && <button className="sticky-cart" onClick={() => setCartOpen(true)}><span><ShoppingBag size={18} /> {t.cart} <b>{count}</b></span><strong>{money(total)}</strong><ArrowRight size={18} /></button>}
    {isCartOpen && <div className="drawer-backdrop" onClick={() => setCartOpen(false)}><aside className="cart-drawer" onClick={(e) => e.stopPropagation()}><div className="drawer-head"><div><p className="section-kicker">{t.table} {table}</p><h2>{t.cart}</h2></div><button className="close-button" onClick={() => setCartOpen(false)}><X size={20} /></button></div>{cart.length === 0 ? <div className="empty-cart"><ShoppingBag size={32} /><h3>{t.empty}</h3><p>{t.emptyHint}</p></div> : <><div className="cart-lines">{cart.map((item) => <div className="cart-line" key={item.id}><div className="cart-line-thumb" style={{ backgroundImage: `url(${item.image})` }} /><div className="cart-line-main"><strong>{item.name[locale]}</strong><span>{money(item.price)}</span><div className="quantity"><button onClick={() => change(item.id, -1)}><Minus size={13} /></button><b>{item.quantity}</b><button onClick={() => change(item.id, 1)}><Plus size={13} /></button></div></div></div>)}</div><div className="drawer-summary"><div><span>{t.total}</span><strong>{money(total)}</strong></div><button className="primary-button" onClick={() => { setCartOpen(false); setOrderOpen(true); }}>{t.order} <ArrowRight size={17} /></button></div></>}</aside></div>}
    {hallOpen && <div className="modal-backdrop"><div className="hall-modal"><div className="drawer-head"><div><p className="section-kicker">{t.hall}</p><h2>{t.chooseTable}</h2><p className="hall-hint">{t.chooseTableHint}</p></div><button className="close-button" onClick={() => setHallOpen(false)}><X size={20} /></button></div><div className="hall-layout"><div className="hall-room"><div className="hall-window">ОКНА</div><div className="hall-tables">{tableOptions.map((number) => <button key={number} className={`hall-table ${table === number ? "selected" : ""}`} onClick={() => { setTable(number); setHallOpen(false); }}><span>{number}</span><small>{table === number ? t.selected : t.free}</small></button>)}</div><div className="hall-bar">BAR · COFFEE HOUSE</div></div></div><div className="hall-legend"><span><i className="selected-dot" /> {t.selected}</span><span><i className="free-dot" /> {t.free}</span></div></div></div>}
    {isOrderOpen && <div className="modal-backdrop"><div className="order-modal">{ordered ? <div className="success-state"><div className="success-icon"><Check size={26} /></div><p className="section-kicker">ORDER RECEIVED</p><h2>Заказ принят</h2><p>Мы уже передали его на кухню. Следить за статусом можно по ссылке ниже.</p><div className="order-number">#{orderNumber}</div><div className="status-mini"><span className="live-dot" /> Готовим ваш заказ <span>≈ 18 мин</span></div><a className="primary-button" href={`/order/${orderNumber}`}>Открыть статус заказа <ArrowRight size={17} /></a></div> : <><div className="drawer-head"><div><p className="section-kicker">{fulfillment === "DINE_IN" ? `${t.table} ${table || "—"}` : t.pickup}</p><h2>{t.order}</h2></div><button className="close-button" onClick={() => setOrderOpen(false)}><X size={20} /></button></div><div className="fulfillment-options"><button className={`fulfillment ${fulfillment === "DINE_IN" ? "active" : ""}`} onClick={() => setFulfillment("DINE_IN")}><Utensils size={19} /><span><strong>{t.delivery}</strong><small>{table ? `${t.table} ${table}` : t.chooseTable}</small></span>{fulfillment === "DINE_IN" && <Check size={17} />}</button><button className={`fulfillment ${fulfillment === "PICKUP" ? "active" : ""}`} onClick={() => setFulfillment("PICKUP")}><ShoppingBag size={19} /><span><strong>{t.pickup}</strong><small>Назовите имя при выдаче</small></span>{fulfillment === "PICKUP" && <Check size={17} />}</button></div>{fulfillment === "DINE_IN" && <button className="change-table-button" onClick={() => setHallOpen(true)}>Выбрать другой стол <ArrowRight size={14} /></button>}<label className="field-label">{t.note}<textarea placeholder="Например, без лука..." /></label>{orderError && <div className="login-error">{orderError}</div>}<div className="drawer-summary"><div><span>{t.total}</span><strong>{money(total)}</strong></div><button className="primary-button" onClick={submitOrder}>Подтвердить заказ <ArrowRight size={17} /></button></div></>}</div></div>}
  </main>;
}
